apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      {{- include "dep-labels" .| nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dep-labels" .| nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.containers.name }}
        image: {{ .Values.containers.image }}
        ports:
        - containerPort: {{ .Values.containers.ports.containerPort }}
